### PR TITLE
Update to Swift 4.1

### PR DESCRIPTION
**Pull request by broomburgo**
Many changes:

- new project structure, focused on separation of abstractions from concrete types;
- use of conditional conformance throughout the whole project;
- new `Function` type that selectively conforms to the protocols depending on the output type;
- a couple of new concrete types.

### CODE REVIEW

**Comment by CodaFi** [comment]
This seems to have reorganized the build to be Carthage-centric.  I would prefer we use Carthage only to fetch the dependencies like the rest of the org - it'll make the eventual migration to SwiftPM-only builds that much easier.

**Comment by broomburgo** [comment]
@CodaFi I fixed the broken `Operadics` dependency in a file, updated the package and checked that `swift build` and `swift test` succeed. Is this ok?

**Comment by broomburgo** [comment]
@CodaFi @bkase guys, can I merge this?

**Comment by CodaFi** [comment]
Still reviewing this patch.  Should have an answer for you in a few hours.

**Comment by CodaFi** [comment]
Didn't realize how much of this was just templating.

LGTM. :shipit:

**Review by CodaFi — APPROVED** [review]

**Pull request merged**
