### PR TITLE
Sourcery for Arbitrary

### PR DESCRIPTION
**Pull request by broomburgo**
I added a Sourcery template (along with annotations in source code for the template to be used) for `Arbitrary` definitions.

There still a type missing: `Endofunction` has a custom definition because its interface is different from the other function wrappers (like `FunctionS`).

For generic types, structs like `TypeOf<T: Arbitrary>: Arbitrary` are generated.

### CODE REVIEW

**Comment by broomburgo** [comment]
I found a way to define types like `TypeOf<T: Arbitrary>: Arbitrary` in Sourcery: not sure what was blocking me initially.

**Review by bkase — APPROVED** [review]
The new sourcery logic is a little crazy, but the auto-generation is really nice. Looks good.

**Comment by bkase** [comment]
I landed the First and Last, could you rebase your changes onto that?

**Comment by broomburgo** [comment]
I merged the changes.

**Pull request merged**
