### PR TITLE
added OptionalEq type

### PR DESCRIPTION
**Pull request by broomburgo**
`OptionalEq` wraps an `Optional` of something `Equatable` and is useful to equip every other type with a `Monoid` definition: it wraps the type into an `Optional` and considers `nil` as the empty case, and `??` as the natural combination.

### CODE REVIEW

**Comment by bkase** [comment]
This implicitly carries the notion of the `First` semigroup. It could be useful to have a `Last` version as well.

What do you think about making something like an `OptionS<S: Semigroup>: Monoid` and then you can do `OptionS<First<T>>` to get the behavior you have in `OptionEq` right now. But you could also do `OptionS<Last<T>>` ?

**Comment by bkase** [comment]
We should definitely document that clearly if we go with that

**Comment by broomburgo** [comment]
You mean the `OptionalS<S: Semigroup>: Semigroup`type? In the use case that spawned the idea I needed a `Monoid`, and the `OptionalM<M: Monoid>: Monoid` type doesn't work in this case.

Maybe I can make a better case if I show what I'm needing this for.

This `OptionalEq` that I'm proposing is almost the same as `FirstM` (takes the first value if it's not `.empty`), with the crucial difference that it doesn't require the wrapped type to be a `Monoid`. I want to use this as the "log" of a `Writer` that I'd like to use for representing a "user session" with some token associated:

```swift
struct Token: Equatable {
    /// stuff
}

typealias Tokenized<T> = Writer<T,LastM<OptionalEq<Token>>>
```

This `Tokenized` writer updates the `Token` with the new value if available, that is, if there's a `Token` in `OptionalEq`: if there's no new `Token` it keeps the previous (thanks to `LastM`).

If `Token` was a `Monoid` I could simply use the following definition:

```swift
typealias Tokenized<T> = Writer<T,LastM<Token>>
```

But it's not, and that's why I needed a way to turn a non-`Monoid` into a `Monoid`, with the semantics of an `Optional`. It's like `ArrayEq` creates a `Monoid` out of every `Equatable`, with the semantics of a list, thus, empty list + appending (so a "free monoid" basically?).

What do you think?

**Comment by bkase** [comment]
Wow I was just writing up a detailed explanation of what I was thinking and I realized what I was saying doesn't work for your example.

I was thinking about `OptionalM`, but `OptionalM` should change to have  Semigroup constraint on `T` instead of the `Monoid` constraint (as we don't query the empty on the wrapped value). I'll make a PR for this now.

We should land this! Sorry, makes sense now!

**Review by bkase — APPROVED** [review]

**Pull request merged**
